version: '3.8'

services:
  # PostgreSQL adatbázis
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=syscode_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Profile microservice
  profile-service:
    build:
      context: ./backend/profile-service
    container_name: profile-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=syscode_db
    depends_on:
      - postgres
    networks:
      - app-network

  # Address microservice
  address-service:
    build:
      context: ./backend/address-service
    container_name: address-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=syscode_db
    depends_on:
      - postgres
    networks:
      - app-network

  # Angular frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - profile-service
      - address-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
